language: go
sudo: false
go:
  - 1.8.x
install:
  - go get -u github.com/mattn/goveralls golang.org/x/tools/cmd/cover github.com/Masterminds/glide github.com/mitchellh/gox github.com/ory/go-acc
  - glide install
script:
  - go-acc -o coverage.out $(glide novendor)
  - go test -race -short $(glide novendor | grep -v cmd)
  - goveralls -service=travis-ci -coverprofile=coverage.out